apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "consumption-report.fullname" . }}
  labels:
    {{- include "consumption-report.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}-volume-permissions
              image: busybox
              command: ["sh", "-c", "chmod -R 777 {{ .Values.outputDir }} && chown -R 1000:1000 {{ .Values.outputDir }}"]
              volumeMounts:
                - name: metric-storage
                  mountPath: {{ .Values.outputDir }}
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if .Values.securityContext }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              {{- end }}
              args:
                - "sh"
                - "-c"
                - |
                  cd {{ .Values.outputDir }}
                  echo "starting metric collection"
                  python /app/resource_monitor.py
              env:
                {{- if .Values.rootCa.enabled }}
                - name: SSL_CERT_FILE
                  value: /etc/ssl/certs/root-ca.crt
                {{- end }}
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: clientId
                - name: CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: clientSecret
                - name: BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: baseUrl
                - name: OUTPUT_DIR
                  value: {{ .Values.outputDir }}
              volumeMounts:
                - name: metric-storage
                  mountPath: {{ .Values.outputDir }}
                {{- if .Values.rootCa.enabled }}
                - name: root-ca
                  mountPath: /etc/ssl/certs/root-ca.crt
                  subPath: runai-ca.pem
                {{- end }}
          volumes:
            - name: metric-storage
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-report-storage
            {{- if .Values.rootCa.enabled }}
            - name: runai-ca
              secret:
                defaultMode: 420
                items:
                - key: runai-ca.pem
                  path: runai-ca.pem
                optional: true
                secretName: {{ .Values.rootCa.secretName }}
            {{- end }}
          restartPolicy: OnFailure

